import { test, expect } from '@playwright/test'
import { ROW_STEP_MS, SCORE_STEP_MS, SCORE_SETTLE_MS } from '../src/lib/useRevealSequence'

const ringUrl = '/#specimen/v1/2026-09-28/00003c24243c0000'

test.describe('逐行显形与顺序计分', () => {
  test.use({ reducedMotion: 'no-preference' })

  test('空白行也依次翻开，最后一行完成后才逐项显示全部得分', async ({ page }, testInfo) => {
    await page.clock.install({ time: new Date('2026-09-28T12:00:00Z') })
    await page.clock.pauseAt(new Date('2026-09-28T12:00:01Z'))
    await page.goto(ringUrl)
    const art = page.locator('.main-fossil .fossil-art')
    await expect(art).toHaveAttribute('data-revealed-rows', '0')
    await expect(page.locator('.row-covered')).toHaveCount(7)
    await expect(page.locator('.row-covered .fossil-cell')).toHaveCount(0)
    await expect(page.locator('.row-flipping')).toHaveAttribute('data-row', '0')
    await expect(page.locator('.row-flipping .row-front')).toHaveCSS('animation-name', 'row-front-flip')
    await expect(page.locator('.field-notes > :not(.section-label)')).toHaveCount(0)
    await expect(page.getByRole('button', { name: '分享发现', exact: true })).toBeDisabled()
    for (let rows = 1; rows <= 8; rows++) {
      await page.clock.runFor(ROW_STEP_MS - 1)
      await expect(art).toHaveAttribute('data-revealed-rows', String(rows - 1))
      await page.clock.runFor(1)
      await expect(art).toHaveAttribute('data-revealed-rows', String(rows))
      await expect(page.locator('.trait-row')).toHaveCount(0)
      await expect(page.locator('.score-total, .overall-rarity')).toHaveCount(0)
      if (rows < 8) await expect(page.locator('.row-flipping')).toHaveAttribute('data-row', String(rows))
      if (rows === 3) await page.screenshot({ path: testInfo.outputPath('rows-revealing.png'), fullPage: true })
    }
    await expect(page.locator('.field-notes')).toHaveAttribute('data-phase', 'scores')
    await expect(page.getByTestId('structure-score')).toHaveCount(0)
    const ascendingIds = ['interior', 'mirror-x', 'mirror-y', 'double-mirror', 'ring', 'hidden-heart', 'connected', 'eye', 'centered', 'rotation']
    for (let index = 0; index < ascendingIds.length; index++) {
      await page.clock.runFor(SCORE_STEP_MS - 1)
      await expect(page.locator('.score-entry')).toHaveCount(index)
      await page.clock.runFor(1)
      await expect(page.locator('.score-entry')).toHaveCount(index + 1)
      await expect(page.locator('.score-total, .overall-rarity')).toHaveCount(0)
      await expect(page.locator('.score-entry .trait-rarity')).toHaveCount(index + 1)
      await expect(page.getByRole('button', { name: '分享发现', exact: true })).toBeDisabled()
      expect(await page.locator('.score-entry').evaluateAll(entries => entries.map(entry => entry.getAttribute('data-trait')))).toEqual(ascendingIds.slice(0, index + 1).reverse())
      await expect(page.locator('.field-notes > .section-label + .score-entry')).toHaveAttribute('data-trait', ascendingIds[index])
      if (index === 0) await page.locator('.score-entry').first().click()
      await expect(page.locator('[data-trait="interior"]')).toHaveAttribute('aria-pressed', 'true')
    }
    await page.clock.runFor(SCORE_SETTLE_MS - 1)
    await expect(page.locator('.score-total, .overall-rarity')).toHaveCount(0)
    await page.clock.runFor(1)
    await expect(page.getByTestId('structure-score')).toHaveText('72分')
    await expect(page.locator('.score-total .overall-rarity')).toBeVisible()
    const values = await page.locator('.score-entry').evaluateAll(entries => entries.map(entry => Number(entry.getAttribute('data-awarded'))))
    expect(values).toEqual([...values].sort((a, b) => b - a))
    await expect(page.locator('.score-reason')).toHaveCount(0)
    const totalBox = await page.locator('.score-total').boundingBox()
    const firstBox = await page.locator('.score-entry').first().boundingBox()
    expect(totalBox!.y + totalBox!.height).toBeLessThanOrEqual(firstBox!.y)
    await expect(page.locator('.field-notes')).toHaveAttribute('data-phase', 'complete')
    await expect(page.getByRole('button', { name: '分享发现', exact: true })).toBeEnabled()
    await expect(page.locator('[data-trait="mirror-x"]')).toHaveAttribute('data-awarded', '0')
    await page.screenshot({ path: testInfo.outputPath('all-structure-scores.png'), fullPage: true })
    await page.getByRole('button', { name: '重播显形与计分，不重新生成' }).click()
    await expect(art).toHaveAttribute('data-revealed-rows', '0')
    await expect(page.locator('.trait-row')).toHaveCount(0)
    await expect(page.locator('.score-total, .overall-rarity')).toHaveCount(0)
    expect(await page.evaluate(() => JSON.parse(localStorage.getItem('fossildle.collection.v1')!).specimens.length)).toBe(0)
    await page.getByRole('link', { name: '结构图鉴', exact: true }).click()
    await page.clock.runFor(20000)
    await expect(page.locator('.trait-row')).toHaveCount(0)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  })

  test('无命中结构在全部翻开后正常完成，得分为零', async ({ page }) => {
    await page.clock.install({ time: new Date('2026-09-28T12:00:00Z') })
    await page.clock.pauseAt(new Date('2026-09-28T12:00:01Z'))
    await page.goto('/#specimen/v2/2026-09-28/0000000000000000')
    await expect(page.locator('.field-notes')).toHaveAttribute('data-phase', 'rows')
    await page.clock.runFor(ROW_STEP_MS * 8)
    await expect(page.locator('.field-notes')).toHaveAttribute('data-phase', 'complete')
    await expect(page.locator('.trait-row')).toHaveCount(0)
    await expect(page.getByTestId('structure-score')).toHaveText('0分')
  })

  test('动画途中切换减少动态效果，立即完成且无遗留计时', async ({ page }) => {
    await page.clock.install({ time: new Date('2026-09-28T12:00:00Z') })
    await page.clock.pauseAt(new Date('2026-09-28T12:00:01Z'))
    await page.goto(ringUrl)
    await expect(page.locator('.field-notes')).toHaveAttribute('data-phase', 'rows')
    await page.clock.runFor(ROW_STEP_MS)
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await expect(page.locator('.field-notes')).toHaveAttribute('data-phase', 'complete')
    await expect(page.locator('.trait-row')).toHaveCount(10)
    await page.clock.runFor(20000)
    await expect(page.getByTestId('structure-score')).toHaveText('72分')
  })
})
