import { test, expect } from '@playwright/test'
import { analyzeFossil, evaluateTraits, fromHex, scoreBreakdown, toHex } from '../src/lib/engine'

const ringWithBranches = '24243c24243c0000'
const branchRoots = scoreBreakdown(evaluateTraits(analyzeFossil(fromHex(ringWithBranches)))).filter(entry => !entry.supersededBy).length

test('手记只保留得分条目和总分；空洞边界原色、枝条灰色', async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.locator('.field-notes > :not(.section-label)')).toHaveCount(0)
  await page.goto(`/#specimen/v1/2026-09-28/${ringWithBranches}`)
  const notes = page.locator('.field-notes')
  const art = page.locator('.main-fossil')
  await expect(notes).toHaveAttribute('data-phase', 'complete')
  await expect(notes.locator(':scope > :not(.section-label):not(.score-entry):not(.score-total)')).toHaveCount(0)
  await expect(notes.locator(':scope > .score-entry')).toHaveCount(branchRoots)
  await expect(notes.locator(':scope > .score-total')).toHaveCount(1)
  await expect(notes.locator('.score-reason')).toHaveCount(0)
  await expect(notes.locator(':scope > .section-label + .score-total')).toHaveCount(1)
  const values = await notes.locator(':scope > .score-entry').evaluateAll(entries => entries.map(entry => Number(entry.getAttribute('data-awarded'))))
  expect(values).toEqual([...values].sort((a, b) => b - a))
  const score = await page.getByTestId('structure-score').textContent()
  const ring = notes.locator('[data-trait="ring"]')
  await ring.locator('.score-entry-head').click()
  await expect(ring.locator('.score-entry-head')).toHaveAttribute('aria-pressed', 'true')
  await expect(notes.locator('.selected')).toHaveCount(1)
  await expect(art.locator('.fossil-cell[data-dimmed="true"]')).toHaveCount(4)
  await expect(art.locator('.fossil-cell[data-dimmed="false"]')).toHaveCount(12)
  for (const index of [2, 5, 10, 13]) {
    await expect(art.locator(`[data-cell="${index}"] .cell-fill`)).toHaveAttribute('fill', '#b2b2aa')
    await expect(art.locator(`[data-cell="${index}"] .cell-shadow`)).toHaveAttribute('fill', '#777770')
  }
  for (const index of [18, 19, 20, 21, 26, 29, 34, 37, 42, 43, 44, 45]) {
    await expect(art.locator(`[data-cell="${index}"] .cell-fill`)).toHaveAttribute('fill', '#a35b3e')
  }
  await expect(art.locator('[data-cell="27"]')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('minimal-notes-cavity-focus.png'), fullPage: true })
  const connected = notes.locator('[data-trait="connected"]')
  await connected.locator('.score-entry-head').click()
  await expect(ring.locator('.score-entry-head')).toHaveAttribute('aria-pressed', 'false')
  await expect(connected.locator('.score-entry-head')).toHaveAttribute('aria-pressed', 'true')
  await expect(notes.locator('.selected')).toHaveCount(1)
  await expect(art.locator('.fossil-cell[data-dimmed="true"]')).toHaveCount(0)
  await connected.locator('.score-entry-head').click()
  await expect(notes.locator('.selected')).toHaveCount(0)
  await expect(art.locator('.fossil-cell[data-dimmed="true"]')).toHaveCount(0)
  await expect(page.getByTestId('structure-score')).toHaveText(score!)
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('fossildle.collection.v1')!).specimens.length)).toBe(0)
})

test('贯穿结构只保留完整行列；键盘取消、分享和重播不保留灰色', async ({ page }) => {
  const board = fromHex('101010ff10101010')
  board[0] = true
  board[63] = true
  await page.goto(`/#specimen/v1/2026-09-28/${toHex(board)}`)
  const art = page.locator('.main-fossil')
  const span = page.locator('.score-entry[data-trait="span"]')
  const cross = page.locator('.score-entry[data-trait="cross"]')
  await expect(page.locator('.field-notes')).toHaveAttribute('data-phase', 'complete')
  await cross.locator('.score-branch-toggle').click()
  await expect(span).toBeVisible()
  await span.click()
  await expect(art.locator('[data-dimmed="true"]')).toHaveCount(2)
  await expect(art.locator('[data-dimmed="false"]')).toHaveCount(15)
  await cross.locator('.score-entry-head').click()
  await expect(span).toHaveAttribute('aria-pressed', 'false')
  await expect(cross.locator('.score-entry-head')).toHaveAttribute('aria-pressed', 'true')
  await cross.locator('.score-entry-head').press('Enter')
  await expect(cross.locator('.score-entry-head')).toHaveAttribute('aria-pressed', 'false')
  await expect(art.locator('[data-dimmed="true"]')).toHaveCount(0)
  await span.click()
  await page.getByRole('button', { name: '分享发现', exact: true }).click()
  await expect(page.locator('.share-preview .fossil-cell[data-dimmed="true"]')).toHaveCount(0)
  await expect(page.locator('.share-preview .fossil-cell[data-dimmed="false"]')).toHaveCount(17)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '重播显形与计分，不重新生成' }).click()
  await expect(page.locator('.field-notes')).toHaveAttribute('data-phase', 'complete')
  await expect(page.locator('.score-entry[aria-pressed="true"]')).toHaveCount(0)
  await expect(art.locator('[data-dimmed="true"]')).toHaveCount(0)
})

test('局部晶核参与计分，高亮、取消选择与重播不改变分数', async ({ page }) => {
  const board = Array<boolean>(64).fill(false)
  for (let y = 2; y <= 4; y++) for (let x = 2; x <= 4; x++) board[y * 8 + x] = true
  board[63] = true
  await page.goto(`/#specimen/v2/2026-09-28/${toHex(board)}`)
  await expect(page.locator('.field-notes')).toHaveAttribute('data-phase', 'complete')
  const score = await page.getByTestId('structure-score').textContent()
  const entry = page.locator('.score-entry[data-trait="crystal-square"]')
  await expect(entry.locator('.trait-points')).toHaveText('+4分')
  await expect(entry).toHaveAttribute('data-awarded', '4')
  await entry.locator('.score-entry-head').click()
  await expect(entry.locator('.score-entry-head')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.main-fossil [data-dimmed="false"]')).toHaveCount(9)
  await expect(page.locator('.main-fossil [data-dimmed="true"]')).toHaveCount(1)
  await expect(page.getByTestId('structure-score')).toHaveText(score!)
  await entry.locator('.score-entry-head').press('Enter')
  await expect(page.locator('.main-fossil [data-dimmed="true"]')).toHaveCount(0)
  await entry.locator('.score-entry-head').click()
  await page.getByRole('button', { name: '重播显形与计分，不重新生成' }).click()
  await expect(page.locator('.field-notes')).toHaveAttribute('data-phase', 'complete')
  await expect(page.locator('.score-entry[aria-pressed="true"][data-trait="crystal-square"]')).toHaveCount(0)
})

test('“任意窗口”结构只高亮最先命中的一处，不平铺全部命中区块', async ({ page }) => {
  const board = fromHex('ff00ff0000000000')
  const stripes = board.filter(Boolean).length
  await page.goto(`/#specimen/v2/2026-09-28/${toHex(board)}`)
  const art = page.locator('.main-fossil')
  await expect(page.locator('.field-notes')).toHaveAttribute('data-phase', 'complete')
  const ribbed = page.locator('.score-entry[data-trait="ribbed"]')
  await expect(ribbed).toHaveAttribute('data-awarded', '7')
  await ribbed.locator('.score-entry-head').click()
  await expect(ribbed.locator('.score-entry-head')).toHaveAttribute('aria-pressed', 'true')
  await expect(art.locator('.fossil-cell[data-dimmed="false"]')).toHaveCount(8)
  await expect(art.locator('.fossil-cell[data-dimmed="true"]')).toHaveCount(stripes - 8)
  const cells = await art.locator('.fossil-cell[data-dimmed="false"]').evaluateAll(nodes => nodes.map(node => Number(node.getAttribute('data-cell'))))
  expect(cells.every(cell => cell < 32 && cell % 8 < 4)).toBe(true)
})

test('平板尺寸的手记没有空白左栏，选择切换后不溢出', async ({ page }) => {
  await page.setViewportSize({ width: 700, height: 1000 })
  await page.goto(`/#specimen/v1/2026-09-28/${ringWithBranches}`)
  await expect(page.locator('.field-notes')).toHaveAttribute('data-phase', 'complete')
  const notes = await page.locator('.field-notes').boundingBox()
  const first = await page.locator('.field-notes > .score-entry').first().boundingBox()
  expect(first!.x).toBeCloseTo(notes!.x, 0)
  expect(first!.width).toBeCloseTo(notes!.width, 0)
  await page.locator('[data-trait="ring"] .score-entry-head').click()
  await page.goto('/#specimen/v1/2026-09-28/00003c24243c0000')
  await expect(page.locator('.field-notes')).toHaveAttribute('data-phase', 'complete')
  await expect(page.locator('.score-entry[aria-pressed="true"]')).toHaveCount(0)
  await expect(page.locator('.main-fossil [data-dimmed="true"]')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('多组证据（象限/连通块）按组用不同颜色区分', async ({ page }) => {
  await page.goto('/#specimen/v2/2026-09-28/cc00000000c0000c')
  const notes = page.locator('.field-notes')
  const art = page.locator('.main-fossil')
  await expect(notes).toHaveAttribute('data-phase', 'complete')
  const quadrants = notes.locator('.score-entry[data-trait="even-quadrants"]')
  await quadrants.locator('.score-entry-head').click()
  await expect(art.locator('.fossil-cell[data-dimmed="false"]')).toHaveCount(8)
  const fills = await art.locator('.fossil-cell[data-dimmed="false"] .cell-fill').evaluateAll(nodes => nodes.map(node => node.getAttribute('fill')))
  expect(new Set(fills).size).toBe(4)
  const groups = await art.locator('.fossil-cell[data-dimmed="false"]').evaluateAll(nodes => nodes.map(node => node.getAttribute('data-group')))
  expect(new Set(groups).size).toBe(4)
  await quadrants.locator('.score-entry-head').click()
  await expect(art.locator('.fossil-cell[data-dimmed="true"]')).toHaveCount(0)
  const restored = await art.locator('.fossil-cell .cell-fill').evaluateAll(nodes => nodes.map(node => node.getAttribute('fill')))
  expect(new Set(restored)).toEqual(new Set(['#a35b3e']))
  await page.goto('/#specimen/v2/2026-09-28/8000001000000001')
  await expect(notes).toHaveAttribute('data-phase', 'complete')
  const islands = notes.locator('.score-entry[data-trait="islands"]')
  await islands.locator('.score-entry-head').click()
  await expect(art.locator('.fossil-cell[data-dimmed="false"]')).toHaveCount(3)
  const islandFills = await art.locator('.fossil-cell[data-dimmed="false"] .cell-fill').evaluateAll(nodes => nodes.map(node => node.getAttribute('fill')))
  expect(new Set(islandFills).size).toBe(3)
})

test('同组未计分条目收进父项的可展开分支且字号更小', async ({ page }) => {
  await page.goto('/#specimen/v1/2026-09-28/00003c24243c0000')
  const notes = page.locator('.field-notes')
  await expect(notes).toHaveAttribute('data-phase', 'complete')
  const eightfold = notes.locator('.score-entry[data-trait="eightfold"]')
  const mirrorX = eightfold.locator('.score-entry[data-trait="mirror-x"]')
  const toggle = eightfold.locator('.score-branch-toggle')
  await expect(toggle).toHaveText(/另有 5 项下位结构/)
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect(mirrorX).toBeHidden()
  await expect(mirrorX).toHaveAttribute('data-awarded', '0')
  await expect(mirrorX.locator('.trait-unscored')).toHaveText('未计分')
  await expect(mirrorX.locator('.trait-points')).toHaveCount(0)
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-expanded', 'true')
  await expect(mirrorX).toBeVisible()
  await expect(mirrorX).toHaveCSS('border-left-color', 'rgb(204, 208, 196)')
  const branchFont = await mirrorX.locator('.trait-name').evaluate(element => parseFloat(getComputedStyle(element).fontSize))
  const headFont = await eightfold.locator('.score-entry-head .trait-name').evaluate(element => parseFloat(getComputedStyle(element).fontSize))
  expect(branchFont).toBeLessThan(headFont)
  const score = await page.getByTestId('structure-score').textContent()
  await mirrorX.click()
  await expect(mirrorX).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.main-fossil [data-dimmed="false"]')).not.toHaveCount(0)
  await expect(page.getByTestId('structure-score')).toHaveText(score!)
  await toggle.click()
  await expect(mirrorX).toBeHidden()
  await expect(page.locator('.main-fossil [data-dimmed="true"]')).toHaveCount(0)
  await expect(page.locator('.score-entry[aria-pressed="true"]')).toHaveCount(0)
})

test('组合上限未计分条目仍平铺显示且可点击高亮', async ({ page }) => {
  await page.goto('/#specimen/v1/2026-09-28/00003c24243c0000')
  await expect(page.locator('.field-notes')).toHaveAttribute('data-phase', 'complete')
  const score = await page.getByTestId('structure-score').textContent()
  const entry = page.locator('.field-notes > .score-entry[data-awarded="0"]')
  await expect(entry).toBeVisible()
  const trait = await entry.getAttribute('data-trait')
  await entry.locator('.score-entry-head').click()
  await expect(entry.locator('.score-entry-head')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.main-fossil [data-dimmed="false"]')).not.toHaveCount(0)
  await expect(page.getByTestId('structure-score')).toHaveText(score!)
  await entry.locator('.score-entry-head').press('Enter')
  await expect(page.locator(`[data-trait="${trait}"] .score-entry-head`)).toHaveAttribute('aria-pressed', 'false')
  await expect(page.locator('.main-fossil [data-dimmed="true"]')).toHaveCount(0)
})
