import { test, expect } from '@playwright/test'
import { fromHex, toHex } from '../src/lib/engine'

const ringWithBranches = '24243c24243c0000'

test('手记只保留得分条目和总分；空洞边界原色、枝条灰色', async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.locator('.field-notes > :not(.section-label)')).toHaveCount(0)
  await page.goto(`/#specimen/v1/2026-09-28/${ringWithBranches}`)
  const notes = page.locator('.field-notes')
  const art = page.locator('.main-fossil')
  await expect(notes).toHaveAttribute('data-phase', 'complete')
  await expect(notes.locator(':scope > :not(.section-label):not(.score-entry):not(.score-total)')).toHaveCount(0)
  await expect(notes.locator(':scope > .score-entry')).toHaveCount(4)
  await expect(notes.locator(':scope > .score-total')).toHaveCount(1)
  await expect(notes.locator('.score-reason')).toHaveCount(0)
  await expect(notes.locator(':scope > .section-label + .score-total')).toHaveCount(1)
  const values = await notes.locator('.score-entry').evaluateAll(entries => entries.map(entry => Number(entry.getAttribute('data-awarded'))))
  expect(values).toEqual([...values].sort((a, b) => b - a))
  const score = await page.getByTestId('structure-score').textContent()
  const eye = notes.locator('[data-trait="eye"]')
  await eye.click()
  await expect(eye).toHaveAttribute('aria-pressed', 'true')
  await expect(notes.locator('.selected')).toHaveCount(1)
  await expect(art.locator('.fossil-cell[data-dimmed="true"]')).toHaveCount(4)
  await expect(art.locator('.fossil-cell[data-dimmed="false"]')).toHaveCount(12)
  for (const index of [2, 5, 10, 13]) {
    await expect(art.locator(`[data-cell="${index}"] .cell-fill`)).toHaveAttribute('fill', '#b2b2aa')
    await expect(art.locator(`[data-cell="${index}"] .cell-shadow`)).toHaveAttribute('fill', '#777770')
  }
  for (const index of [18, 19, 20, 21, 26, 29, 34, 37, 42, 43, 44, 45]) {
    await expect(art.locator(`[data-cell="${index}"] .cell-fill`)).toHaveAttribute('fill', '#a35b3e')
  }
  await expect(art.locator('[data-cell="27"]')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('minimal-notes-cavity-focus.png'), fullPage: true })
  await notes.locator('[data-trait="ring"]').click()
  await expect(eye).toHaveAttribute('aria-pressed', 'false')
  await expect(notes.locator('[data-trait="ring"]')).toHaveAttribute('aria-pressed', 'true')
  await expect(notes.locator('.selected')).toHaveCount(1)
  await expect(art.locator('.fossil-cell[data-dimmed="true"]')).toHaveCount(4)
  await notes.locator('[data-trait="connected"]').click()
  await expect(art.locator('.fossil-cell[data-dimmed="true"]')).toHaveCount(0)
  await eye.click()
  await eye.click()
  await expect(notes.locator('.selected')).toHaveCount(0)
  await expect(art.locator('.fossil-cell[data-dimmed="true"]')).toHaveCount(0)
  await expect(page.getByTestId('structure-score')).toHaveText(score!)
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('fossildle.collection.v1')!).specimens.length)).toBe(0)
})

test('贯穿结构只保留完整行列；键盘取消、分享和重播不保留灰色', async ({ page }) => {
  const board = fromHex('101010ff10101010')
  board[0] = true
  board[63] = true
  await page.goto(`/#specimen/v1/2026-09-28/${toHex(board)}`)
  const art = page.locator('.main-fossil')
  const span = page.locator('.score-entry[data-trait="span"]')
  const cross = page.locator('.score-entry[data-trait="cross"]')
  await expect(page.locator('.field-notes')).toHaveAttribute('data-phase', 'complete')
  await span.click()
  await expect(art.locator('[data-dimmed="true"]')).toHaveCount(2)
  await expect(art.locator('[data-dimmed="false"]')).toHaveCount(15)
  await cross.click()
  await expect(span).toHaveAttribute('aria-pressed', 'false')
  await expect(cross).toHaveAttribute('aria-pressed', 'true')
  await cross.press('Enter')
  await expect(cross).toHaveAttribute('aria-pressed', 'false')
  await expect(art.locator('[data-dimmed="true"]')).toHaveCount(0)
  await span.click()
  await page.getByRole('button', { name: '分享发现', exact: true }).click()
  await expect(page.locator('.share-preview .fossil-cell[data-dimmed="true"]')).toHaveCount(0)
  await expect(page.locator('.share-preview .fossil-cell[data-dimmed="false"]')).toHaveCount(17)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '重播显形与计分，不重新生成' }).click()
  await expect(page.locator('.field-notes')).toHaveAttribute('data-phase', 'complete')
  await expect(page.locator('.score-entry[aria-pressed="true"]')).toHaveCount(0)
  await expect(art.locator('[data-dimmed="true"]')).toHaveCount(0)
})

test('平板尺寸的手记没有空白左栏，选择切换后不溢出', async ({ page }) => {
  await page.setViewportSize({ width: 700, height: 1000 })
  await page.goto(`/#specimen/v1/2026-09-28/${ringWithBranches}`)
  await expect(page.locator('.field-notes')).toHaveAttribute('data-phase', 'complete')
  const notes = await page.locator('.field-notes').boundingBox()
  const first = await page.locator('.score-entry').first().boundingBox()
  expect(first!.x).toBeCloseTo(notes!.x, 0)
  expect(first!.width).toBeCloseTo(notes!.width, 0)
  await page.locator('[data-trait="eye"]').click()
  await page.goto('/#specimen/v1/2026-09-28/00003c24243c0000')
  await expect(page.locator('.field-notes')).toHaveAttribute('data-phase', 'complete')
  await expect(page.locator('.score-entry[aria-pressed="true"]')).toHaveCount(0)
  await expect(page.locator('.main-fossil [data-dimmed="true"]')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
